// <auto-generated />
using System;
using IoT_System.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IoT_System.Infrastructure.Migrations.IoT
{
    [DbContext(typeof(IoTDbContext))]
    partial class IoTDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("IoT.System")
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IoT_System.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ApiKeyExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ApiKey")
                        .IsUnique()
                        .HasDatabaseName("IX_Devices_ApiKey");

                    b.HasIndex("IsActive", "CreatedOn")
                        .HasDatabaseName("IX_Devices_IsActive_CreatedOn");

                    b.ToTable("Devices", "IoT.System");
                });

            modelBuilder.Entity("IoT_System.Domain.Entities.DeviceAccessPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PermissionType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "GroupId")
                        .HasDatabaseName("IX_DeviceAccessPermissions_DeviceId_GroupId");

                    b.HasIndex("DeviceId", "RoleId")
                        .HasDatabaseName("IX_DeviceAccessPermissions_DeviceId_RoleId");

                    b.HasIndex("DeviceId", "UserId")
                        .HasDatabaseName("IX_DeviceAccessPermissions_DeviceId_UserId");

                    b.ToTable("DeviceAccessPermissions", "IoT.System");
                });

            modelBuilder.Entity("IoT_System.Domain.Entities.DeviceField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CriticalMax")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("CriticalMin")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<int>("DataType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("WarningMax")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("WarningMin")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "FieldName")
                        .IsUnique()
                        .HasDatabaseName("IX_DeviceFields_DeviceId_FieldName");

                    b.HasIndex("DeviceId", "IsActive", "DisplayOrder")
                        .HasDatabaseName("IX_DeviceFields_DeviceId_IsActive_DisplayOrder");

                    b.ToTable("DeviceFields", "IoT.System");
                });

            modelBuilder.Entity("IoT_System.Domain.Entities.DeviceMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DataFormat")
                        .HasColumnType("integer");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("MeasurementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ParsedSuccessfully")
                        .HasColumnType("boolean");

                    b.Property<string>("ParsingErrors")
                        .HasColumnType("text");

                    b.Property<string>("RawData")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn")
                        .HasDatabaseName("IX_DeviceMeasurements_CreatedOn");

                    b.HasIndex("DeviceId", "MeasurementDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_DeviceMeasurements_DeviceId_MeasurementDate");

                    b.HasIndex("DeviceId", "ParsedSuccessfully")
                        .HasDatabaseName("IX_DeviceMeasurements_DeviceId_ParsedSuccessfully");

                    b.ToTable("DeviceMeasurements", "IoT.System");
                });

            modelBuilder.Entity("IoT_System.Domain.Entities.FieldMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DataFormat")
                        .HasColumnType("integer");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceFieldPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TransformationPipeline")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FieldId", "DataFormat", "IsActive")
                        .HasDatabaseName("IX_FieldMappings_FieldId_DataFormat_IsActive");

                    b.ToTable("FieldMappings", "IoT.System");
                });

            modelBuilder.Entity("IoT_System.Domain.Entities.FieldMeasurementValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MeasurementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("FieldId")
                        .HasDatabaseName("IX_FieldMeasurementValues_FieldId");

                    b.HasIndex("MeasurementId", "FieldId")
                        .HasDatabaseName("IX_FieldMeasurementValues_MeasurementId_FieldId");

                    b.ToTable("FieldMeasurementValues", "IoT.System");
                });

            modelBuilder.Entity("IoT_System.Domain.Entities.MeasurementDateMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DataFormat")
                        .HasColumnType("integer");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceFieldPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TransformationPipeline")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "DataFormat", "IsActive")
                        .HasDatabaseName("IX_MeasurementDateMappings_DeviceId_DataFormat_IsActive");

                    b.ToTable("MeasurementDateMappings", "IoT.System");
                });

            modelBuilder.Entity("IoT_System.Domain.Entities.DeviceAccessPermission", b =>
                {
                    b.HasOne("IoT_System.Domain.Entities.Device", "Device")
                        .WithMany("AccessPermissions")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("IoT_System.Domain.Entities.DeviceField", b =>
                {
                    b.HasOne("IoT_System.Domain.Entities.Device", "Device")
                        .WithMany("Fields")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("IoT_System.Domain.Entities.DeviceMeasurement", b =>
                {
                    b.HasOne("IoT_System.Domain.Entities.Device", "Device")
                        .WithMany("Measurements")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("IoT_System.Domain.Entities.FieldMapping", b =>
                {
                    b.HasOne("IoT_System.Domain.Entities.DeviceField", "Field")
                        .WithMany("Mappings")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");
                });

            modelBuilder.Entity("IoT_System.Domain.Entities.FieldMeasurementValue", b =>
                {
                    b.HasOne("IoT_System.Domain.Entities.DeviceField", "Field")
                        .WithMany("MeasurementValues")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IoT_System.Domain.Entities.DeviceMeasurement", "Measurement")
                        .WithMany("FieldValues")
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("IoT_System.Domain.Entities.MeasurementDateMapping", b =>
                {
                    b.HasOne("IoT_System.Domain.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("IoT_System.Domain.Entities.Device", b =>
                {
                    b.Navigation("AccessPermissions");

                    b.Navigation("Fields");

                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("IoT_System.Domain.Entities.DeviceField", b =>
                {
                    b.Navigation("Mappings");

                    b.Navigation("MeasurementValues");
                });

            modelBuilder.Entity("IoT_System.Domain.Entities.DeviceMeasurement", b =>
                {
                    b.Navigation("FieldValues");
                });
#pragma warning restore 612, 618
        }
    }
}
